### ISSUE TITLE
data sources in vest-ca-2020.ipynb

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/pdv-ca#1]
What's the data source of `./raw-from-source/2018 County Lines/cb_2018_us_county_5m.shp`?  Is vestshape.csv converted from VEST's ca_2020.dbf?  Did you transform or modify either vestshape.csv or `./raw-from-source/source/state results fixed.csv`?  Thanks.

**Comment by peter-redistricting-data-hub** [comment]
You can find that here: https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html

I'll let Chris follow up with your other question

**Comment by rootsmusic** [comment]
Thanks Peter for the source files.

**Comment by ChrisDoPoliticalData** [comment]
Hey there the data source for "./raw-from-source/2018 County Lines/cb_2018_us_county_5m.shp" was used as a spot check for the counties of San Bernardino and Kern County to look at differences between the VEST's results and the boundary lines of the census. 

In regards to the second question "./raw-from-source/source/state results fixed.csv" was modified with VEST's processing steps found in the documentation. That was manually deconsolidation precinct by precinct for each of the counties listed in VEST's documentation. Lastly, "vestshape.csv " was not modified but called in csv format after the first call to rejoin shape file geometries to the pivoted and joined election results as I had removed the geometries to make it easier to use the file in various other formats. Let me know if you have any more questions @rootsmusic
