### ISSUE TITLE
vest_er_val in vest-ca-2020.ipynb

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/pdv-ca#2]
@ChrisDoPoliticalData If `./raw-from-source/vest/vestshape.csv` is supposed to equal `./raw-from-source/vest/ca_2020.shp` except file format, then why does vestshape.csv have several hundred rows fewer?  In the file conversion, both SRPREC_KEY and SRPREC columns converted from text format to scientific notation with mixed text and numerical digits (filter vestshape.csv for 'Humboldt' COUNTY).

**Comment by ChrisDoPoliticalData** [comment]
I believe I answered both of these in the previous question, but in terms of ./raw-from-source/vest/ca_2020.shp no changes were made to the vest file the vest file was called back in to bring geometries back into the election results. 

for, "What in the state's SOV did you fix to output ./raw-from-source/source/state results fixed.csv? Thanks.," the statewide database filed was edited in accordance to VEST's documentation: "Precinct results that were combined by the Statewide Database were separated according to the 2020 Statement of the Vote from the registrars of the following counties: Glenn, El Dorado, Imperial, Inyo, Madera, Mendocino, San Joaquin, San Luis Obispo, Shasta, Sierra, Siskiyou, Sutter, Tuolumne."

**Comment by rootsmusic** [comment]
@ChrisDoPoliticalData If ./raw-from-source/vest/vestshape.csv is supposed to equal ./raw-from-source/vest/ca_2020.shp except file format, then why does vestshape.csv have several hundred rows fewer than ca_2020.shp? In the file conversion, both SRPREC_KEY and SRPREC columns converted from text format to scientific notation (filter vestshape.csv for Humboldt COUNTY).

P.S. since you answered my question in the other issue, I revised this one to focus on one file.

**Comment by rootsmusic** [comment]
@peter-redistricting-data-hub  Have you confirmed whether `./raw-from-source/vest/vestshape.csv` was supposed to equal `./raw-from-source/vest/ca_2020.shp` (except file format)?  If you've confirmed, then please covert the file format again.  Thanks.

**Comment by peter-redistricting-data-hub** [comment]
Hey, unfortunately I was not able to confirm whether that was the case and given some other work priorities I had to move on to other work, so I don't think I'll get to this in the foreseeable future.
